global:
  scrape_interval: 15s


scrape_configs:
  - job_name: 'search-api'
    static_configs:
      - targets: ['search-api:80']
  - job_name: 'web'
    static_configs:
      - targets: ['web:80']
  - job_name: 'auth'
    static_configs:
      - targets: ['auth:80']
  - job_name: 'load-balancer'
    static_configs:
      - targets: ['load-balancer:80']
